### ISSUE TITLE
White screen on Raspberry Pi

### ISSUE THREAD

**Issue by megomes** [gosu/gosu#285]
Hello,

I have a test project which doesn't draw anything. The only thing that it does is declare and load some images on the initialization:

    require 'gosu'

    class GameWindow < Gosu::Window
        def initialize
    	super(950, 500, true)
        @background_image_1 = Gosu::Image.new("images/Background.png")
        @background_image_2 = Gosu::Image.new("images/Background.png")
        @background_image_3 = Gosu::Image.new("images/Background.png")
        @background_image_4 = Gosu::Image.new("images/Background.png")
        @background_image_5 = Gosu::Image.new("images/Background.png")
        @background_image_6 = Gosu::Image.new("images/Background.png") # MAX NUMBER
        @background_image_7 = Gosu::Image.new("images/Background.png")
    end

    def update
    end

    def draw
    end

    end

    window = GameWindow.new 
    window.show

When I execute on my mac, it works perfectly (shows a black screen or render a image if I draw it)

When I execute it on my Raspberry pi (Raspbian on Raspberry B+ or Raspberry 2. Both have the same error) it shows a White Screen and it doesn't render anything if I draw it.

BUT, if I remove that last line *(@background_image_7)*, it will work just as it is in my mac.

I have a bigger project that has the same problem. A limited number of images declared. If i surpass this number, the screen will be white, no matter what.

The image *(images/Background.png)* is a PNG 848x480 with only 8KB

Thank you in advance!

**Comment by jlnr** [comment]
Yep, @sebastianludwig had the same issue when loading images on the Raspi. It runs out of VRAM really, really fast. A 848x480 PNG image will occupy a single 1024x1024px texture because of how Gosu's allocation works (it's very conservative with texture sizes), times 4 because Gosu always uses R8G8B8A8 textures -- so 4 MB per image, not 8 KB :)

The Pi (at least the first version) allows you to choose how much RAM you want to use for VRAM, and how much for the system. You can try increasing the amount of VRAM, see for example (this SO thread)[http://raspberrypi.stackexchange.com/questions/673/what-is-the-optimum-split-of-main-versus-gpu-memory].

If the you sometimes discard images (remove all references to them) and Ruby does not free up the VRAM, try calling `GC.run` after removing the last reference. If this helps but isn't reliable enough, please +1 issue #229.

**Comment by megomes** [comment]
Thank you, @jlnr! I'll try that right now!

**Comment by sebastianludwig** [comment]
You can check out https://github.com/sebastianludwig/Raspicture to see how I managed to keep two 1024x1024 images in memory (if that's enough for you).

**Comment by megomes** [comment]
Thanks, @sebastianludwig! I will definitely check that out! I was like crazy trying to understand what was happening...

**Comment by megomes** [comment]
It worked perfectly! Thank you, guys!
