### ISSUE TITLE
OSX Yosemite error with long songs.

### ISSUE THREAD

**Issue by alanmesquita** [gosu/gosu#301]
When I try to play a long song it is stopped. In linux operating normally, however I'm having this problem on OS X Yosemite.

Code example:

```
Bundler.require :default

class GameWindow < Gosu::Window
  def initialize
    super 600, 300
    self.caption = "Teste"

    play_theme
  end

  def update
  end

  def draw
  end

  private

  def play_theme
    @theme = Gosu::Sample.new("./media/imperial_march.wav")
    @theme.play(0.5,1, true)
  end
end
```

I have tried with other music and the same error.

**Comment by jlnr** [comment]
Oops, I'm not sure how I've managed to ignore this issue for five years after assigning it to myself. I assume this response will be a bit too late, but here we go.

The long answer is that Gosu::Sample is not designed for long audio files, it will try to decode everything into memory so that it can play back the sound in one shot using OpenAL. Gosu::Song, on the other hand, will decode bite-sized audio chunks and feed them to OpenAL every now and then. I have never really tested what happens if the contents of a Sample are too long to feed them to OpenAL all at once, but it seems likely that playback would stop after a while, as you've experienced it.

The short answer is that Gosu::Sample and Gosu::Song will internally use the same logic in Gosu 1.0. See #441 for an early initial approach, but I'll have to rebase this on the new SDL_Sound audio back end.
