### ISSUE TITLE
Specifying color when drawing text seems to make text invisible

### ISSUE THREAD

**Issue by naiyt** [gosu/gosu#309]
I'm running on OSX 10.10.5, if that helps.

If I specify the color when drawing using a `Gosu::Font`, text seems to disappear, regardless of the color. According to the docs, the default text color is `0xff_ffffff` -- even if I specify that, I can't seem to see the text.

[Here's a gist demonstrating](https://gist.github.com/naiyt/e7922fd56dca171cb443).

Not sure if I'm doing something wrong, or if there's a bug. Any advice would be appreciated, thanks!

![screen shot 2016-01-10 at 1 55 35 pm](https://cloud.githubusercontent.com/assets/1728948/12223939/df366fa8-b7a1-11e5-88a6-92a3185cf893.png)

**Comment by jlnr** [comment]
The `scale_x`/`scale_y` arguments come before `color`:

https://libgosu.org/rdoc/Gosu/Font.html#draw-instance_method

(Yeah, these long argument lists are not pretty... :/)

Also, passing `color = 0xff_ffffff` as an argument creates a local variable `color`, assigns the value, then passes the value to the function. Just passing `0xff_ffffff` is fine. It shows up as `color = 0xff_ffffff` in the method's argument list only because that is the default value for the `color` parameter.

**Comment by naiyt** [comment]
Oh, right, rookie mistake. I seem to always revert to thinking Ruby supports Python style default/keyword arguments...

Thanks for the help! Having a lot of fun with Gosu.

**Comment by jlnr** [comment]
Glad to hear that! And I also thought it looked like Python :)
