### ISSUE TITLE
Analog gamepad input support

### ISSUE THREAD

**Issue by jtuttle** [gosu/gosu#412]
It would be great to be able to read input from the analog sticks on a gamepad (-1.0 ... +1.0) for finer control over directional input.

**Comment by jlnr** [comment]
This topic came up in #gosu, @shawn42 noted that it could be as simple as providing a callback `axis_motion(id, value)` in `Window`. (Not sure about the name yet)

**Comment by cyberarm** [comment]
Should this callback have 3 arguments, i.e. `axis_motion(gamepad_id, axis_id, value)`?

Which SDL Event should be used to capture input: [SDL_ControllerAxisEvent](https://wiki.libsdl.org/SDL_ControllerAxisEvent), [SDL_JoyAxisEvent](https://wiki.libsdl.org/SDL_JoyAxisEvent), or both?

https://wiki.libsdl.org/SDL_Event

**Comment by jlnr** [comment]
Gosu uses the SDL_Controller API when available for a device, SDL_Joy otherwise.

Right now, buttons have different constants for different gamepads: GP_4_BUTTON_4, so it would be more consistent to have GP_4_AXIS_X or something. Redesigning everything to be less C-ish and more object-oriented is an orthogonal task.

**Comment by cyberarm** [comment]
Closing this since [Gosu.axis](https://www.rubydoc.info/gems/gosu/Gosu%2Eaxis) was added to Gosu.
