### ISSUE TITLE
draw_rect seems to be missing from gosu

### ISSUE THREAD

**Issue by DavidMWM** [gosu/gosu#418]
demo_shapes.rb:13:in `draw': undefined method `draw_rect' for #<DemoWindow:0x007fb9798d0e70> (NoMethodError)
Did you mean?  draw_line

Also seems to be missing in:

https://github.com/gosu/gosu/blob/master/src/Graphics.cpp

**Comment by jlnr** [comment]
`draw_rect` is only available in the Ruby version of Gosu, but that's actually a bit silly, now that I think about it. It's defined here:

https://github.com/gosu/gosu/blob/master/ext/gosu/gosu.i#L274-L280

I'll use this issue as a reminder to just move it into Graphics.cpp.

Have you tried calling `Gosu.draw_rect(...)` instead of calling it directly on Window? That should work. But it's a strange inconsistency and I think I'll look into that as well.

**Comment by jlnr** [comment]
Fixed in 2920b7a6450d82f00be5dc0977384510c2fda581
