### ISSUE TITLE
Floating point exception: 8 error 

### ISSUE THREAD

**Issue by theSharif** [gosu/gosu#419]
the gosu examples menu will open however every time i attempt to open an example i get a Floating point exception: 8  error and the example(s) shuts down

**Comment by jlnr** [comment]
Oh wow. I've just tried to run `gosu-examples` and I don't even get so far:

> /usr/local/lib/ruby/gems/2.4.0/gems/gosu-0.12.1/lib/gosu/compat.rb:101:in `from_text': Cannot load default font (RuntimeError)

This is a new one. I'll look into both issues.

**Comment by jlnr** [comment]
Never mind, my error was caused by accidentally(?) disabling the Arial font on macOS, which happens to be Gosu's default font.

@theSharif Did this happen on macOS? There was a compiler bug in recent versions of Xcode (or the command-line tools) that could trigger a division by zero in Gosu's BMP loading code. I have released Gosu 0.13.1 which fixes the issue.
