### ISSUE TITLE
Gosu does not support Ruby 2.5.0 on Windows

### ISSUE THREAD

**Issue by naiasuzuki** [gosu/gosu#427]
Hi, this is my first time using gosu and i'm not sure if what i'm doing is the issue or if it's a issue with gosu but after I install gosu, and try to test if with this code in https://github.com/gosu/gosu/wiki/Getting-Started-on-Windows I get this error: 
```
Traceback (most recent call last):
        6: from C:/Users/------/Documents/Personal/programming/Ruby/Game/Game.rb:1:in `<main>'
        5: from C:/Ruby25-x64/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        4: from C:/Ruby25-x64/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        3: from C:/Ruby25-x64/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/gosu-0.13.2-x64-mingw32/lib/gosu.rb:25:in `<top (required)>'
        1: from C:/Ruby25-x64/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
C:/Ruby25-x64/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- gosu.so (LoadError)
```

I'm using ruby 2.5.0 x64 on windows 10. Like I said this is my first time using gosu and i'm sorry I'm just doing something wrong. 
Thank you!

**Comment by naiasuzuki** [comment]
Thanks! I'll try downgrading

**Comment by AngusWP** [comment]
How do I downgrade?

**Comment by jlnr** [comment]
You install Ruby 2.4 via RubyInstaller, and choose to update your PATH to point to this installation; there's a checkbox for this in the installer, I think.

**Comment by blacktm** [comment]
I've been working a lot lately with the new RubyInstaller for Ruby 2.4+ using MSYS2. This error is _probably_ due to the installer environment not being able to find DLLs needed by the gem (these paths now have to be [explicitly defined](https://github.com/oneclick/rubyinstaller2/wiki/For-gem-developers#-dll-loading)). I've been doing something like...

```
RubyInstaller::Runtime.add_dll_directory(File.expand_path('~/../../usr/local/bin'))
```

...before the native extension gets loaded. I'm not sure where the dependent DLLs get placed in Gosu, but if you know their path(s), try using the approach above before calling `require 'gosu'`. Good luck!

**Comment by Kjarrigan** [comment]
@blacktm This is actually already done in gosu.

_Snippet from lib/gosu.rb_
```ruby
    # Make DLLs available as shown here:
    # https://github.com/oneclick/rubyinstaller2/wiki/For-gem-developers
    require 'ruby_installer'
    RubyInstaller::Runtime.add_dll_directory(binary_path)
```

But Gosu needs to be explicitly updated for newer ruby versions as stated here: https://github.com/gosu/gosu/blob/master/dependencies/msvcrt-ruby/README.md

Unfortunately I don't have a running windows at the moment. So feel free to try it out yourself and send an PR to enable 2.5 support. :smiley:

**Comment by jlnr** [comment]
It's on my roadmap too, but I've already merged some parts of my text rewrite to `master` and I don't want to push another 0.13 release. This issue will probably remain blocked until I finish the text stuff... :/

**Comment by jlnr** [comment]
Anyway, thanks for the pointer (both of you). I had actually forgotten that this code already exists in Gosu :D

**Comment by KataraAang** [comment]
Thanks! Finally it worked!

**Comment by jlnr** [comment]
I don't have time to properly announce this release right now, but I've pushed a new gem (v0.13.3) that includes support for Ruby 2.5 on Windows.

**Comment by jlnr** [comment]
The 64-bit version of the 0.13.3 was missing, not sure how that happened – I've just pushed it again. If you had any issues installing Gosu 0.13.3, please try again.

**Comment by CorbeauDeMinuit** [comment]
I've tried running my script and it says 
C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55: in 'require': cannot load such file -- gosu (LoadError) 
from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55: in 'require'

**Comment by jlnr** [comment]
@CorbeauDeMinuit The error message mentions Ruby 2.4, not Ruby 2.5 (which this issue is about). Was there any unusual output when you installed Gosu? Which version of Gosu is this?

**Comment by CorbeauDeMinuit** [comment]
There was no unusual output but I am using gosu 0.14.5

**Comment by Kjarrigan** [comment]
@CorbeauDeMinuit please be a bit more specific so we can try to debug your issue:

1. Please open a new issue since you're using ruby 2.4 and this issues is about 2.5
2. Provide a minimal failing script and add the whole stacktrace
3. I assume you're using a version from here https://rubyinstaller.org?
   * Do you have installed the version with or without devkit? 
   * Whats the output of `ridk version`?
