### ISSUE TITLE
Alternatives to chipmunk?

### ISSUE THREAD

**Issue by sagotsky** [gosu/gosu#492]
I'm trying to get into gosu.  Chipmunk won't install on new rubies.  The newest one I got it to work on is 2.3.3.  

I asked about this on their github and was told chipmunk is unmaintained.  https://github.com/chipmunk-rb/chipmunk/issues/25#issuecomment-478708621  Is there another physics engine that works with gosu on modern rubies?

**Comment by jlnr** [comment]
The only other free physics engine that I know of is Box2D, and it doesn't seem to have any usable Ruby bindings either. I think your best bet would be to fix the Chipmunk bindings, or to start with games that don't require elaborate physics. Most 2D games work just fine with hand-written physics, maybe even better! But of course I don't know your plans :)

Closing this since this is not really an issue. If you want to explore a fix for Chipmunk with Ruby 2.6, I recommend joining the Gosu discord server or some kind of Ruby forum where people might know C.
