### ISSUE TITLE
HTML colours support in Gosu directly?

### ISSUE THREAD

**Issue by rubyFeedback** [gosu/gosu#579]
So this is now about colours.

I had a look at:

  https://www.rubydoc.info/github/gosu/gosu/master/Gosu/Color

Some constants exist for colours like blue. That's useful.

We also have .rgba() which is similar to gtk I guess; in ruby-gtk3
I can use:

    Gtk::RGBA.new() I think ... also needs 4 values.

There are also HTML colours such as steelblue, royalblue, crimson,
tomato and so forth.

An example can be seen here: https://www.w3schools.com/colors/colors_hex.asp

(I use only the downcased names though.)

Could these colour names be added to Gosu::Color?

It's not a big deal because I have a colours-related gem that already does convert
the names into RGB values, so I can just use the provided .rgba() method anyway,
but I think I will also use some custom modifications to class Gosu::Color, to make
working with this simpler for me (e. g. using certain colours, so I will probably
also just ad-hoc add names such as Gosu::Color.steelblue() as method for that
colour or so. I use that for ruby-gtk3 as well by the way, and for my www-related
projects. Easier on my brain, but I totally understand if Gosu itself does not get
direct support for this, since it is a library for many users, not just for me alone :D )

**Comment by jlnr** [comment]
Thanks for the suggestion. I had considered HTML/CSS colors when I first added these colors constants. I'm glad I didn't add them though, because keeping constants in sync between C++, Ruby, Rdoc, the gosu.cr and cyberarm's ffi-ruby gem is...painful. Less is more! One good thing about Ruby is that you can easily add helpers to Gosu::Color from your own code.
