### ISSUE TITLE
API suggestion for TextInput

### ISSUE THREAD

**Issue by rubyFeedback** [gosu/gosu#580]
Here is the docu: https://www.rubydoc.info/github/gosu/gosu/master/Gosu/TextInput

I am using it right now; already got things working for a basic hangman game. :D

I may publish this soon ... I already wrote a commandline variant, and ruby-gtk3
bindings; this is one reason why I am looking at gosu (and libui too by the way).

Anyway. There is one thing that appears to be missing right now for TextInput.

I'd like the ability to justify the text; in particular to center it. The default seems
to be left-align.

I assume it is possible to get centered text by modifying the subclass I use, but
I think it would be much simpler if something like .center() or .justify(:left) or 
:center and so could be added directly to TextInput.

You could ask what the behaviour for .center() would be. Well, I think the most
logical choice here would be to first enter the character representation, and
afterwards look at the whole string, and re-align with equal padding on both
sides. I think this is the most expected behaviour; cursor would remain
at the right text boundary though, by default at least. But I am sure there may
be other solutions; I am just trying to explain what I think may make sense.

(On a side note, is it possible to make multi-coloured text? In the same sentence
of a text that is. I haven't looked at that yet. In ruby-gtk3 we can use markup
and <b> bold tags and such. Very primitive but kind of works quite ok-ish.)

**Comment by jlnr** [comment]
I try not to force any visuals on users of Gosu, that's why the TextInput class is 100% abstract and the game/application has to provide all rendering code. If you use left-aligned text as in the TextInput sample from `gosu-examples`, then it will be left-aligned; but that's totally up to you! :)

And yes, Gosu supports `<c=rrggbb>` pseudo-XML tags, as well as `<b>`, `<i>`, and (half-heartedly) `<u>`. That's why there is Font::draw_text as well as Font::draw_markup, same for Image.from_text/Image.from_markup, etc.
