### ISSUE TITLE
Memory allocation error when using Font#[]=

### ISSUE THREAD

**Issue by runnerpack** [gosu/gosu#652]
When I run this code:
```ruby
class EmuWin < Gosu::Window
	def initialize
		super 80 * 8, 50 * 16

		@mono = Gosu::Font.new(16, {name: Gosu::default_font_name, retro: true})

		monotiles = Gosu::Image.load_tiles('./SuperFont.png', 8, 16, {tileable: true, retro: true})

		(0..255).each { |i|
			@mono[i.chr] = monotiles[i]
		}
```

I get the following error:

```
emulator.rb:24:in `set_image': std::bad_alloc (RuntimeError)
        from emulator.rb:24:in `block in initialize'
        from emulator.rb:23:in `each'
        from emulator.rb:23:in `initialize'
        from emulator.rb:60:in `new'
        from emulator.rb:60:in `<main>'
```

"SuperFont.png" is a 128x256 pixel PNG with an 8x16 pixel ASCII font.
If I limit the range of codepoints to 0..127, it works fine, but I really want those extended ASCII characters!
Are there some codepoints that aren't allowed?
Does the codepoint have to already exist in the originally loaded font?
Is this a Ruby limitation, or a Gosu one?

**Comment by jlnr** [comment]
(Edited the issue to use triple-`)

The bad_alloc error looks like a bug in Gosu that I will look into, this method should throw another kind of exception when given invalid UTF-8.

The string is invalid because 255.chr returns a single byte `"\xff"`, but that's not how codepoint 255 is encoded in UTF-8: https://www.compart.com/de/unicode/U+00FF

This should fix the issue:
```ruby
255.chr.force_encoding("ISO-8859-1").encode("UTF-8") # => "ÿ"
```

(This works because the first Unicode code points correspond to the Latin-1 encoding; https://stackoverflow.com/a/57413375)

I guess it would be nice if `Font[]=` supported indexing by code point? But this is such a niche feature already that I'm not sure if I want to touch it right now.

**Comment by runnerpack** [comment]
> (Edited the issue to use triple-`)
(Thanks! 😅)

> The string is invalid because 255.chr returns a single byte `"\xff"`, but that's not how codepoint 255 is encoded in UTF-8: https://www.compart.com/de/unicode/U+00FF

I was thinking it was probably an encoding issue, but the bad_alloc thing threw me off 🤷🏻‍♂️

> This should fix the issue (using 255 as an example here):
> ```ruby
> 255.chr.force_encoding("ISO-8859-1").encode("UTF-8") # => "ÿ"
> ```

Wow, thanks for the fix!

> I guess it would be nice if `Font[]=` supported indexing by code point? But this is such a niche feature already that I'm not sure if I want to touch it right now.

I'll look into that and maybe submit a PR 🤔

Thanks for the quick response 👍🏻

**Comment by jlnr** [comment]
^ see the comment above, this has already been fixed on master.
