### ISSUE TITLE
[Question] Is there a way to clear the screen in semi-transparency for a blur effect?

### ISSUE THREAD

**Issue by akicho8** [gosu/gosu#675]
I'm interested in creative coding with Gosu, rather than Processing, as it's easier to use.
However, I'm not sure how to clear the screen considering transparency and how to achieve a blur effect.

You can write it like this in Processing.

```JavaScript
function setup() {
  createCanvas(windowWidth, windowHeight);
}

function draw() {
  background(0, 10);
  rect(mouseX, mouseY, 100, 100);
}
```

<img width="792" alt="screenshot2023_10-16_10_51_58" src="https://github.com/gosu/gosu/assets/808955/d28bd0eb-a591-43f1-8b99-f904be462165">

Demo: https://openprocessing.org/sketch/2045343

Here is the version written in Gosu, but it only displays a simple square.

```ruby
require "gosu"
RUBY_VERSION                    # => "3.2.2"
Gosu::VERSION                   # => "1.4.6"

class App < Gosu::Window
  def draw
    Gosu.draw_rect(mouse_x, mouse_y, 100, 100, Gosu::Color::WHITE)
  end

  new(640, 480).show
end
```

I would appreciate it if you could advise me if there is a better way.

This also seems to be related: #402

**Comment by jlnr** [comment]
The screen has to be redrawn from scratch for every single frame, and because Gosu uses double(?) buffering, this is not just an arbitrary restriction either.

The easiest way to achieve the effect you have shown is to remember all previous rectangles and actively redraw them in an ever darker shade of gray / layer transparent black rectangles on top, and then remove those rectangles from the array that have become invisible to put a limit on the memory/CPU usage.

The code certainly won't look as nice, but if you want to do more things like this, you could probably build a thin framework on top of Gosu that remembers previous frames.

**Comment by akicho8** [comment]
Thanks for your reply.

You are right, it is difficult to accurately represent the previous drawing with the double buffering method. However, the blur effect is not a problem as long as there is some kind of afterimage and it looks like that.

I have actually done something similar with SDL before, using the double buffering method, and it did not feel particularly strange.

**Comment by rubyFeedback** [comment]
Is "creative coding" similar to context free grammar? For instance
https://www.contextfreeart.org/gallery/search.php?t=new&num=25

That would be kind of cool if someone would give a try at that.
